export enum ActionTypes {
  INPUT_FOCUSED = 'INPUT_FOCUSED',
  INPUT_BLURRED = 'INPUT_BLURRED',
  SEARCH_TEXT_ENTERED = 'SEARCH_TEXT_ENTERED',
  SHOW_RESULTS = 'SHOW_RESULTS',
  HIDE_RESULTS = 'HIDE_RESULTS',
  LIST_BLURRED = 'LIST_BLURRED',
  ITEM_FOCUSED = 'ITEM_FOCUSED',
  ITEM_SELECTED = 'ITEM_SELECTED',
}
