export enum ActionTypes {
  INPUT_FOCUSED = 'INPUT_FOCUSED',
  INPUT_BLURRED = 'INPUT_BLURRED',
  SEARCH_TEXT_ENTERED = 'SEARCH_TEXT_ENTERED',
  ITEM_FOCUSED = 'ITEM_FOCUSED',
  ITEM_SELECTED = 'ITEM_SELECTED',
}
