export enum ActionTypes {
  INPUT_FOCUSED = 'INPUT_FOCUSED',
  INPUT_BLURRED = 'INPUT_BLURRED',
  SEARCH_TEXT_ENTERED = 'SEARCH_TEXT_ENTERED',
  COUNTRY_FOCUSED = 'COUNTRY_FOCUSED',
  COUNTRY_SELECTED = 'COUNTRY_SELECTED',
}
